#!/usr/bin/env ruby

ENGINE_ROOT = File.expand_path('..', __dir__)
ENGINE_PATH = File.expand_path('../lib/spree_world_pay_ifrmae/engine', __dir__)

require 'rails/all'
require 'rails/engine/commands'
